---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vault-secrets-buildkite-plugin
  description: A buildkite plugin to map Vault secrets to Step environments variables

  annotations:
    backstage.io/source-location: url:https://github.com/elastic/vault-secrets-buildkite-plugin/
    github.com/project-slug: elastic/vault-secrets-buildkite-plugin
    github.com/team-slug: elastic/platform-dev-flow

  tags:
    - buildkite
    - vault

spec:
  type: buildkite-plugin
  owner: group:platform-dev-flow
  lifecycle: beta

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-vault-secrets-buildkite-plugin
  description: Buildkite Pipeline for vault-secrets-buildkite-plugin repository

  tags:
    - buildkite
    - vault

  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/vault-secrets-buildkite-plugin

spec:
  type: buildkite-pipeline
  owner: group:platform-dev-flow
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      description: Vault Secrets Buildkite Plugin Pipeline
      name: Vault Secrets Buildkite Plugin
    spec:
      repository: elastic/vault-secrets-buildkite-plugin
      pipeline_file: ./.buildkite/pipeline.yml

      teams:
        everyone:
          access_level: BUILD_AND_READ
        release-eng: {}
        platform-dev-flow:
          access_level: MANAGE_BUILD_AND_READ
