steps:
  - label: "Pre-commit"
    command: ".buildkite/scripts/pre-commit.sh"
    plugins:
      - elastic/hermit#v1.0.0
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
