steps:
  - label: "Pre-commit"
    command: ".buildkite/scripts/pre-commit.sh"
    plugins:
      - elastic/hermit#v1.0.0
    agents:
      image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
  - label: ":sparkles: Buildkite plugin Lint"
    plugins:
      - plugin-linter#v3.0.0:
          id: elastic/vault-secrets
    agents:
      provider: "gcp"
      image: family/ci-ubuntu-2204
  - group: "Unit tests"
    steps:
      - label: "Unit test field with variable mapping"
        command: ".buildkite/scripts/test-field-var-mapping.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              field: "message"
              env_var: "MESSAGE"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test json with variable mapping"
        command: ".buildkite/scripts/test-json-var-mapping.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              env_var: "MESSAGE"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test field with variable based on secret path"
        command: ".buildkite/scripts/test-field.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              field: "message"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test json with variable based on secret path"
        command: ".buildkite/scripts/test-json.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test field with variable based on secret path and depth 1"
        command: ".buildkite/scripts/test-field-path-depth-1.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              field: "message"
              path_depth: "1"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test json with variable based on secret path and depth 1"
        command: ".buildkite/scripts/test-json-path-depth-1.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              path_depth: "1"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test field with variable based on secret path and depth 3"
        command: ".buildkite/scripts/test-field-path-depth-3.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              field: "message"
              path_depth: "3"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
      - label: "Unit test json with variable based on secret path and depth 1"
        command: ".buildkite/scripts/test-json-path-depth-3.sh"
        plugins:
          - elastic/vault-secrets#$BUILDKITE_COMMIT:
              path: "secret/ci/elastic-vault-secrets-buildkite-plugin/test"
              path_depth: "3"
        agents:
          image: "docker.elastic.co/ci-agent-images/ubuntu-build-essential"
