#!/bin/bash
set -eo pipefail

MAX_RETRIES=3

check_command() {
  command=$1
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "Could not find the $command cli"
    exit 1
  fi
}

generate_variable_name() {
  path=$1
  field=$2

  var_name=$(basename "$path")

  if [ -n "$field" ]; then
    var_name="${var_name}_$field"
  fi

  # _SECRET suffix is used to ensure the variable content is redacted in Buildkite logs
  # https://buildkite.com/docs/pipelines/managing-log-output#redacted-environment-variables
  final_var_name=$(echo "$var_name" | tr "[:lower:]" "[:upper:]" | tr "-" "_")_SECRET
  echo "$final_var_name"
}

retry() {
  local retries=0
  local exit_code=1
  local command=$*

  while [ "$retries" -lt "$MAX_RETRIES" ] && [ "$exit_code" -ne 0 ]; do
    eval "$command"
    exit_code=$?

    if [ "$exit_code" -ne 0 ]; then
      sleep 5
    fi

    retries=$((retries + 1))
  done

  if [ "$exit_code" -ne 0 ]; then
    echo "Command failed after $MAX_RETRIES retries." >&2
    exit 1
  fi
}

check_command vault

secret=""
if [ -n "${BUILDKITE_PLUGIN_VAULT_SECRETS_FIELD}" ]; then
  secret=$(retry vault kv get -field="${BUILDKITE_PLUGIN_VAULT_SECRETS_FIELD}" "${BUILDKITE_PLUGIN_VAULT_SECRETS_PATH}")
else
  secret=$(retry vault kv get -format=json "${BUILDKITE_PLUGIN_VAULT_SECRETS_PATH}")
fi

if [ -n "${BUILDKITE_PLUGIN_VAULT_SECRETS_ENV_VAR}" ]; then
  eval "${BUILDKITE_PLUGIN_VAULT_SECRETS_ENV_VAR}='${secret}'"
  export "${BUILDKITE_PLUGIN_VAULT_SECRETS_ENV_VAR?}"
else
  variable_name=$(generate_variable_name "$BUILDKITE_PLUGIN_VAULT_SECRETS_PATH" "$BUILDKITE_PLUGIN_VAULT_SECRETS_FIELD")
  eval "${variable_name}='${secret}'"
  export "${variable_name?}"
fi
