#!/bin/bash

EXPECTED_ENV_PATH_NAME='TEST_ELASTIC_CO_MESSAGE_SECRET'

if [ -z "$TEST_ELASTIC_CO_MESSAGE_SECRET" ]; then
  echo "[ERROR] TEST_ELASTIC_CO_MESSAGE_SECRET variable is empty or not defined."
  exit 1
fi

if [ "$TEST_ELASTIC_CO_MESSAGE_SECRET" == "$EXPECTED_ENV_PATH_NAME" ]; then
  echo "TEST_ELASTIC_CO_MESSAGE_SECRET is correct: $TEST_ELASTIC_CO_MESSAGE_SECRET"
  exit 0
else
  echo "[ERROR] Expected: $EXPECTED_ENV_PATH_NAME - Got: $TEST_ELASTIC_CO_MESSAGE_SECRET"
  exit 1
fi
